apiVersion: v1
kind: Pod
metadata:
  name: centos-pod
spec:
  containers:
  - name: centos-container
    image: centos:7
    command: ["sleep", "1000"]   
    envFrom:
     - secretRef:
        name: game-secret



---
apiVersion: v1
kind: Secret
metadata:
  name: game-secret
data:
  MONGODB_USERNAME: YWRtaW4K
  MONGODB_PASSWORD: cGFzc3dvcmQK