apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "2"
      limits:
        memory: "128Mi"
        cpu: "4"

# ---
# # multi-container pod 
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-pod                    
# spec:                              
#   containers:                        
#   - name: nginx                   
#     image: nginx:1.14.2
#     resources:
#       requests:
#         memory: "64Mi"
#         cpu: "0.1"
#       limits:
#         memory: "128Mi"
#         cpu: "0.2"

#   - name: alpine                  
#     image: httpd
#     resources:
#       requests:
#         memory: "64Mi"
#         cpu: "0.1"
#       limits:
#         memory: "128Mi"
#         cpu: "0.2"